# This workflow uses the community-driven "GitHub Metrics" action 'lowlighter/metrics',
# main repo at https://github.com/lowlighter/metrics

# personalized configuration for me.
name: Metrics
on:
  # Schedule updates (each day at 00:00 UTC)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LiAuTraver
          template: classic
          base: header, activity, community, metadata
          # plugin_gists: no
          # plugin_introduction: no
          # plugin_introduction_title: yes
          # plugin_isocalendar: no
          # plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 14
          plugin_languages_analysis_timeout_repositories: 7
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 6
          # plugin_languages_recent_categories: markup, programming
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          # plugin_people: no
          # plugin_projects: no
          # plugin_stars: no
